# .travis.yml

os: linux
dist: focal

language: cpp

python:
  - "3.8"

addons:
  apt:
    packages:
      - googletest
      - qtbase5-dev
      - python3-dev

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - conda activate test-environment
  - python setup.py install

before_script:
  - cmake --version
  # Build and install Google Test
  - mkdir gtest-build
  - cd gtest-build
  - >
    cmake
    -DBUILD_GTEST:BOOL=ON
    -DCMAKE_INSTALL_PREFIX:PATH=${TRAVIS_BUILD_DIR}/gtest
    /usr/src/googletest
  - cmake --build .
  - cmake --build . --target install
  - cd - 

script:
  - mkdir build
  - cd build
  - export CMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/gtest:${CMAKE_PREFIX_PATH}
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
